pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                git 'https://github.com/Lukky175/Devops_Project.git'
            }
        }

        stage('Run Disk Utilization Script') {
            steps {
                script {
                    // Ensure the Disk Utilization script is executable
                    sh 'chmod +x ./ShellScripts_For_Pipeline/Disk_Utilisation.sh'
                    // Run the Disk Utilization script
                    sh './ShellScripts_For_Pipeline/Disk_Utilisation.sh'
                }
            }
        }

        stage('Run Process Management Script') {
            steps {
                script {
                    // Ensure the Process Management script is executable
                    sh 'chmod +x ./ShellScripts_For_Pipeline/processmanagement.sh'
                    // Run the Process Management script
                    sh './ShellScripts_For_Pipeline/processmanagement.sh'
                }
            }
        }
    }
}
